version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kristal-clean
    deploy:
      labels:
        - traefik.http.routers.my-container.rule=Host(`kristalclean.pl`)
        # switch on TLS
        - traefik.http.routers.blog.tls=true
        # tell Traefik to serve it from port 443
        - traefik.http.routers.blog.entrypoints=websecure
        # Traefik shall get a certificate using the letsEncryptResolver
        - traefik.http.routers.blog.tls.certresolver=letsEncryptResolver
    ports:
      - '8081:3000'
