version: '3.9'

networks:
  traefik_web:
    name: traefik_web
    external: true

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        - traefik.enabled=true
        - traefik.docker.network=traefik_web
    container_name: kristal-clean
    networks:
      - traefik_web
    ports:
      - '8081:3000'
