version: '3'

networks:
  traefik_web:
    name: traefik_web
    external: true

services:
  kristalclean:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - traefik_web
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.kristalclean.rule=Host(`kristalclean.pl`)'
