version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-next
    deploy:
      labels:
        com.example.description: 'This label will appear on the web service'
    ports:
      - '8081:3000'
    volumes:
      - .:/app
      - /app/node_modules
